# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.14.2
    displayName: "Install Node.js"

  - script: |
      cd handlelisteApp/client-app
      rm -rf node_modules
    displayName: "Remove node_modules"

  - script: |
      cd handlelisteApp/client-app
      rm package-lock.json
    displayName: "Remove package-lock.json"

  - script: |
      cd handlelisteApp/client-app
      npm install
    displayName: "Run npm install"

  - script: |
      cd handlelisteApp/client-app
      npm run test:ci
    displayName: "Run npm test"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit" # Options: JUnit, NUnit, VSTest, xUnit
      testResultsFiles: "**/junit.xml"
    displayName: "Publish test results"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "**/cobertura-coverage.xml"
    displayName: "Publish Code Coverage"

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"

  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "Install dotnet-reportgenerator-globaltool"
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . dotnet-reportgenerator-globaltool

  - task: DotNetCoreCLI@2
    displayName: "Test $(buildConfiguration)"
    inputs:
      command: test
      projects: $(solution)
      arguments: --configuration $(BuildConfiguration) --collect "XPlat Code Coverage"

  - script: reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml;$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetDir:$(Build.SourcesDirectory)/TestResults/Coverage/Reports -reporttypes:Cobertura
    displayName: "Create Code Coverage Reports"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish Code Coverage"
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/TestResults/Coverage/Reports/Cobertura.xml
      failIfCoverageEmpty: false

  - task: DotNetCoreCLI@2
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "handlelisteApp/handlelisteApp.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
