// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using handlelisteApp.Context;

namespace handlelisteApp.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    [Migration("20210224124759_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("handlelisteApp.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShoppingListID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("ItemID");

                    b.HasIndex("ShoppingListID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("handlelisteApp.Models.ItemOnShoppingList", b =>
                {
                    b.Property<int>("ItemOnShoppingListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemOnShoppingListID");

                    b.HasIndex("ItemID");

                    b.ToTable("ItemOnShoppingLists");
                });

            modelBuilder.Entity("handlelisteApp.Models.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShoppingListID");

                    b.HasIndex("UserID");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("handlelisteApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("handlelisteApp.Models.Item", b =>
                {
                    b.HasOne("handlelisteApp.Models.ShoppingList", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListID");
                });

            modelBuilder.Entity("handlelisteApp.Models.ItemOnShoppingList", b =>
                {
                    b.HasOne("handlelisteApp.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("handlelisteApp.Models.ShoppingList", b =>
                {
                    b.HasOne("handlelisteApp.Models.User", null)
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("handlelisteApp.Models.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("handlelisteApp.Models.User", b =>
                {
                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
